export const BEERS_FETCH_SUCCESS = 'BEERS_FETCH_SUCCESS';
export const BEERS_FETCH_LOADING = 'BEERS_FETCH_LOADING';
export const BEERS_FETCH_FAILURE = 'BEERS_FETCH_FAILURE';
export const UPDATE_SEARCH_RESULT = 'UPDATE_SEARCH_RESULT';
