export const BEERS_FETCH_SUCCESS = 'BEERS_FETCH_SUCCESS';
export const BEERS_FETCH_LOADING = 'BEERS_FETCH_LOADING';
export const BEERS_FETCH_FAILURE = 'BEERS_FETCH_FAILURE';
export const UPDATE_SEARCH_RESULT = 'UPDATE_SEARCH_RESULT';
export const SET_BEER_ID = 'SET_BEER_ID';
export const UPDATE_HOME_BEERS = 'UPDATE_HOME_BEERS';
export const UPDATE_FAVOURITES = 'UPDATE_FAVOURITES'; // Too generic
export const UPDATE_SEARCH_BEERS = 'UPDATE_SEARCH_BEERS';

